### ISSUE TITLE
댓글

### ISSUE THREAD

**Issue by arch-spatula** [yunjunhojj/kanban-front#5]

**Comment by arch-spatula** [comment]
```sh
git checkout -b feature/comment
```

**Comment by arch-spatula** [comment]
`git push`를 해주시면 중간에 제가 확인하기 더 편해집니다. 

난이도가 꽤 높은 작업입니다. `Comment` 컴포넌트에서 `store`로 `commentInputSlice`로 데이터를 보내고 `CreateComment` 컴포넌트에서 store로 접근하고 input의 state를 업데이트하겠습니다.

`Comment` 컴포넌트 수정버튼 클릭 -> `commentInputSlice` 로직 처리 -> `store`에서 commentInput을 저장 -> `CreateComment` 컴포넌트 `useSelector` -> `setState`합니다. -> 저장 `boardSlice`로 `updateCommentThunk`

**Comment by HongguLim** [comment]
> `git push`를 해주시면 중간에 제가 확인하기 더 편해집니다.
> 
> 난이도가 꽤 높은 작업입니다. `Comment` 컴포넌트에서 `store`로 `commentInputSlice`로 데이터를 보내고 `CreateComment` 컴포넌트에서 store로 접근하고 input의 state를 업데이트하겠습니다.
> 
> `Comment` 컴포넌트 수정버튼 클릭 -> `commentInputSlice` 로직 처리 -> `store`에서 commentInput을 저장 -> `CreateComment` 컴포넌트 `useSelector` -> `setState`합니다. -> 저장 `boardSlice`로 `updateCommentThunk`

넵 알겠습니다. 오늘 잠깐 일이있어서 외출하고 오후에는 정예부대 숙제하고 하느라 못건드렸네요ㅜㅜ 말씀하신것 확인해보겠습니다!!

**Comment by arch-spatula** [comment]
CRUD 끝
